# [异常处理 ( Exceptions )](https://www.dartlang.org/guides/language/language-tour#exceptions)

异常是程序在执行时发生的一个意外错误说明。Dart 支持异常的抛出和捕获。如果发生的异常没有被捕获，那么将会引发异常隔离，说白了就是程序会被终止。

相对于 Java 来说，Dart 所有的异常都是未检查异常，在方法上不需要去显示的声明可能抛出的异常类型，也不用必须去捕获异常。

Dart 不仅仅能抛出 Exception 和 Error，还支持抛出任何非空类型的对象。

下列表格是 Dart 预定义的一些异常类型：

异常类型|异常描述
---------------|-------------
DeferredLoadException|延迟库无法加载时抛出
FormatException|当字符串或某些其他数据不具有预期格式且无法解析或处理时抛出异常。
IntegerDivisionByZeroException|当数字除以零时抛出。
IOException|所有与Inupt-Output相关的异常的基类。
IsolateSpawnException|无法创建隔离时抛出。
TimeoutException|在等待异步结果时发生计划超时时抛出。

异常涉及相关的关键字：

关键字|说明
---------------|-------------
throw| 显示的抛出异常
try| 后面跟可能会执行的代码块，代表尝试去执行，但可能会发生异常
on| 后面跟需要处理的异常类型和处理逻辑，用于执行补救措施 可以 catch 连用
catch|捕获异常实例，用于需要获取异常信息的场景，可与 on 连用
rethrow|继续抛出异常
finally|执行与异常无关且必要执行的代码块

## 抛出异常 ( Throw )

Dart 使用 throw 关键字来显示的抛出异常，应该在合适的时间捕获异常，以免发生程序被终止。

示例代码：

```
main(){

  //抛出一个指定异常类型的异常
//  throw FormatException("'Expected at least 1 section");

  //抛出一个任意的异常信息(未指定异常类型)
  //注意：正式环境通常是实现Exception 或 Error
//  throw 'Out of llamas!';//字符串类型
//  throw 1;//int 类型

  //抛出一个ERROR
  throw Error;

}

///抛出异常是一个表达式，Dart 可以使用 => 抛出异常，同样可在任意书写表达式的地方抛出异常
void distanceTo(String other) => throw UnimplementedError();
```

[throwException.dart 代码](../../dart/exception/throwException.dart)

## 捕获异常 ( Catch )

捕获异常的语法：

```
try{
	//可能发生异常的代码块
} on Exception1{
	//这里写处理异常类型1的代码
} catch(e){
	//这里写处理异常并需要获取实例的代码
}
```

代码示例：

```
main() {
//  _catchOne();
//  _catchMultiException();
//  _catchMultiType();
  _rethrowHandle();
}

///处理一种异常类型
_catchOne() {
  try {
    throw FormatException("抛出一个FormatException类型异常");
  } on FormatException {
    //关键字 on
    //在此处理异常
    print("处理异常");
  }
}

///处理多种异常类型
_catchMultiException() {
  try {
//    throw FormatException("抛出一个 FormatException 类型异常");
//    throw Exception("抛出一个 Exception 类型异常");
//    throw Error;
    throw "抛出一个字符串类型";
  } on FormatException {
    print("处理FormatException异常");
  } on Exception catch (e) {
    print("处理 Exception 异常： $e");
  } catch (e) {
    print('处理任意类型异常： $e');
  }
}

///处理捕获多种异常类型(异常对象和栈对象)
_catchMultiType() {
  try {
//    throw FormatException("抛出一个 FormatException 类型异常");
    throw "抛出一个字符串";
  } on Exception catch (e) {
    print("处理 Exception 异常： $e");
  } catch (e, s) {
    //拿到异常对象和栈对象
    print('Exception details:\n $e');
    print('Stack trace:\n $s');
  }
}

///处理重新抛出的异常
_rethrowHandle() {
  try {
    _rethrow();
  } catch (e) {
    print("处理重新抛出的异常：$e");
  }
}

///处理异常并使用 rethrow 重新抛出异常
_rethrow() {
  try {
    throw "抛出一个异常";
  } on String catch (e) {//这里的异常类型是 String ，证明了 Dart 支持可抛出非空的任何对象
    print("处理：$e");
    rethrow; //使用 rethrow 重新抛出异常
  }
}
```

[catchException.dart 代码](../../dart/exception/catchException.dart)


## 必然执行 ( Finally )

finally 关键字的作用是不管是否异常，确保某些代码始终执行。

```
main() {
//  _finally1();
  _finally2();
}

_finally1() {
  try {
    int n = 1;
//    throw "抛出异常";
  } finally {
    //确保这句代码始终执行
    print("finally 执行语句");
  }
}

_finally2() {
  try {
    throw "抛出异常";
  } catch (e) {
    print("处理：$e");
  } finally {
    //确保这句代码始终执行
    print("finally 执行语句");
  }
}
```

[finallyException.dart 代码](../../dart/exception/finallyException.dart)

## 自定义异常
虽然 Dart 支持抛出任何非空对象的异常，但为了在开发中便于管理异常，最好开始通过自定义异常的形式，使查看代码时一目了然，也便于统一处理异常。

代码示例：

```
main(){
  int value = -1;
  try{
    if(value <0){
      //抛出异常
      throw CustomException("Value 值不能小于 0");
    }
  } on CustomException catch (e){
    print("异常：${e.getErrMsg()}");
  }
}

///自定义类型
class CustomException implements Exception{

  String msg;//异常说明

  CustomException(this.msg);

  String getErrMsg() => msg;
}
```
[customException.dart 代码](../../dart/exception/customException.dart)

